### ISSUE TITLE
project[:referred_project_ids].each is nil

### ISSUE THREAD

**Issue by seansparkman** [bitrise-steplib/steps-xamarin-ios-test#23]
# <NoMethodError: undefined method `each' for nil:NilClass>

--- Stack trace: ---
["/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise551011363/step_src/xamarin-builder/analyzer.rb:193:in `block in build_test_commands'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise551011363/step_src/xamarin-builder/analyzer.rb:168:in`each'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise551011363/step_src/xamarin-builder/analyzer.rb:168:in `build_test_commands'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise551011363/step_src/xamarin-builder/builder.rb:53:in`build_test'", "/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise551011363/step_src/step.rb:201:in `<main>'"]
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | xamarin-ios-test@1.0.2 (exit code: 1)                        | 102 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: ...//github.com/bitrise-steplib/steps-xamarin-ios-test/issues |
| Source: https://github.com/bitrise-steplib/steps-xamarin-ios-test            |
+----+--------------------------------------------------------------+----------+

![screen shot 2016-06-16 at 5 08 47 pm](https://cloud.githubusercontent.com/assets/991351/16134808/081710ac-33e5-11e6-9c2c-77b40dc97816.png)
![screen shot 2016-06-16 at 5 08 37 pm](https://cloud.githubusercontent.com/assets/991351/16134807/080f1b0e-33e5-11e6-8859-a2740e9a839d.png)

**Comment by godrei** [comment]
@seansparkman Thanks for reporting!
Can you please also copy-past the log between the config and `--- Stack trace: ---`, there sould be the error inspect.

**Comment by seansparkman** [comment]
`
+------------------------------------------------------------------------------+
| (9) xamarin-ios-test@1.0.2                                                   |
+------------------------------------------------------------------------------+
| id: xamarin-ios-test                                                         |
| version: 1.0.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-06-16T14:48:56-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |

[34mConfigs:[0m
- project: plusone.sln
- configuration: Debug
- platform: iPhoneSimulator
- test_to_run: 
- simulator_device: iPhone 6s Plus
- simulator_os: latest
  compare: 8.1 <> 8.1
  pair: [8, 8] - diff: 0
  pair: [1, 1] - diff: 0
  compare: 8.1 <> 8.2
  pair: [8, 8] - diff: 0
  pair: [1, 2] - diff: -1
  compare: 8.2 <> 8.3
  pair: [8, 8] - diff: 0
  pair: [2, 3] - diff: -1
  compare: 8.3 <> 8.4
  pair: [8, 8] - diff: 0
  pair: [3, 4] - diff: -1
  compare: 8.4 <> 9.0
  pair: [8, 9] - diff: -1
  compare: 9.0 <> 9.1
  pair: [9, 9] - diff: 0
  pair: [0, 1] - diff: -1
  compare: 9.1 <> 9.2
  pair: [9, 9] - diff: 0
  pair: [1, 2] - diff: -1
  compare: 9.2 <> 9.3
  pair: [9, 9] - diff: 0
  pair: [2, 3] - diff: -1
- lates_simulator_os: iOS 9.3
- simulator_UDID: 67795F57-6F10-4802-9B2C-8BD70C010182

[34m["\"/Applications/Xamarin Studio.app/Contents/MacOS/mdtool\"", "build", "\"-c:Debug|iPhoneSimulator\"", "\"plusone.sln\"", "\"-p:plusone\""][0m

Xamarin Studio Build Tool
Loading solution: /Users/vagrant/git/plusone.sln
   Loading projects ..
Building: plusone (Debug|iPhoneSimulator)
   MessageView.cs(43,18): warning CS0659: `MessageBar.MessageView' overrides Object.Equals(object) but does not override Object.GetHashCode()
   MessageBarManager.cs(591,21): warning CS0219: The variable`dismiss' is assigned but its value is never used
   Resources/Images.xcassets: actool warning : A 83.5x83.5@2x app icon is required for iPad apps targeting iOS 9.0 and later
   Resources/Images.xcassets: actool warning : The image set "BubbleIncoming" has an unassigned child.
   Resources/Images.xcassets: actool warning : The app icon set "AppIcons" has an unassigned child.
   Resources/Images.xcassets: actool warning : The image set "BubbleIncoming" has an unassigned child.
   Resources/poweredby-black-61.png:  warning : Input PNG is already optimized for iPhone OS.  Copying source file to destination...
   /Library/Frameworks/Mono.framework/Versions/4.4.0/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'Newtonsoft.Json' not resolved
   ViewControllers/BaseViewController.cs(352,22): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/AccountViewController.cs(52,22): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/InterestsViewController.cs(23,30): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/InterestsViewController.cs(92,21): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(81,22): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Event/EventViewController.cs(92,22): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Event/BidConfirmedViewController.cs(17,30): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/MyPlusOne/BidderProfileViewController.cs(34,30): warning CS1998: Async block lacks`await' operator and will run synchronously
   AppDelegate.cs(112,10): warning CS0219: The variable `result' is assigned but its value is never used
   ViewControllers/LoginJoin/JoinViewController.cs(96,9): warning CS0219: The variable`validationErrorMessages' is assigned but its value is never used
   ViewControllers/LoginJoin/LoginViewController.cs(44,23): warning CS0168: The variable `exception' is declared but never used
   ViewControllers/Account/AccountViewController.cs(68,5): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/AccountViewController.cs(69,5): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/AccountViewController.cs(70,5): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/AccountViewController.cs(87,7): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/AccountViewController.cs(88,7): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/AccountViewController.cs(103,6): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/AccountViewController.cs(107,6): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/AccountViewController.cs(108,6): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/InterestsViewController.cs(42,5): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/InterestsViewController.cs(43,5): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/InterestsViewController.cs(56,21): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/InterestsViewController.cs(61,21): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/InterestsViewController.cs(64,21): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/InterestsViewController.cs(85,5): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/InterestsViewController.cs(86,5): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(70,5): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(73,5): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(292,7): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(293,7): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(294,7): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(313,6): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(318,6): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(319,6): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(356,6): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(363,6): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(371,6): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Account/ProfileViewController.cs(164,25): warning CS0168: The variable`exception' is declared but never used
   ViewControllers/Event/EventsViewController.cs(321,17): warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using `await' operator or calling`Wait' method
   ViewControllers/Event/EventViewController.cs(81,7): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Event/EventViewController.cs(82,7): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Event/EventViewController.cs(87,6): warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using `await' operator
   ViewControllers/Event/EventViewController.cs(125,4): warning CS0162: Unreachable code detected
   ViewControllers/Event/EventViewController.cs(198,5): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/Event/EventViewController.cs(203,5): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/Event/EventViewController.cs(204,5): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/MyPlusOne/MyBidsViewController.cs(68,21): warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using `await' operator
   ViewControllers/MyPlusOne/MyPostsViewController.cs(69,21): warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using`await' operator
   ViewControllers/MyPlusOne/WatchingViewController.cs(68,21): warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using `await' operator
   ViewControllers/PostEvent/EventLocationViewController.cs(116,34): warning CS0168: The variable`geolocationException' is declared but never used
   ViewControllers/PostEvent/EventLocationViewController.cs(161,35): warning CS0168: The variable `geolocationException' is declared but never used
   Sources/SuggestionSearchViewSource.cs(36,34): warning CS0168: The variable`geolocationException' is declared but never used
   ViewControllers/MyPlusOne/WonViewController.cs(68,21): warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using `await' operator
   ViewControllers/MyPlusOne/BidderProfileViewController.cs(81,5): warning CS1998: Async block lacks`await' operator and will run synchronously
   ViewControllers/MyPlusOne/BidderProfileViewController.cs(84,5): warning CS1998: Async block lacks `await' operator and will run synchronously
   ViewControllers/MyPlusOne/BidderProfileViewController.cs(88,5): warning CS1998: Async block lacks`await' operator and will run synchronously
   Views/MyPlus1InfoView.cs(37,6): warning CS1998: Async block lacks `await' operator and will run synchronously
   Views/MyPlus1InfoView.cs(38,21): warning CS1998: Async block lacks`await' operator and will run synchronously
   Views/MyPlus1InfoView.cs(39,21): warning CS1998: Async block lacks `await' operator and will run synchronously
   AppDelegate.cs(168,36): warning CS0414: The private field`plusone.AppDelegate.ApsKey' is assigned but its value is never used
   ViewControllers/LoginJoin/JoinEnterDetailsViewController.cs(17,15): warning CS0169: The private field `plusone.ViewControllers.JoinEnterDetailsViewController._currentField' is never used
   ViewControllers/Filters/FilterBidTypeViewController.cs(15,51): warning CS0169: The private field`plusone.FilterBidTypeViewController._viewSource' is never used
/Users/vagrant/git/MessageBarLib/MessageView.cs(43,18) : warning CS0659: `MessageBar.MessageView' overrides Object.Equals(object) but does not override Object.GetHashCode()
/Users/vagrant/git/MessageBarLib/MessageBarManager.cs(591,21) : warning CS0219: The variable`dismiss' is assigned but its value is never used
/Users/vagrant/git/plusone/Resources/Images.xcassets : warning: A 83.5x83.5@2x app icon is required for iPad apps targeting iOS 9.0 and later
/Users/vagrant/git/plusone/Resources/Images.xcassets : warning: The image set "BubbleIncoming" has an unassigned child.
/Users/vagrant/git/plusone/Resources/Images.xcassets : warning: The app icon set "AppIcons" has an unassigned child.
/Users/vagrant/git/plusone/Resources/Images.xcassets : warning: The image set "BubbleIncoming" has an unassigned child.
/Users/vagrant/git/plusone/Resources/poweredby-black-61.png : warning: Input PNG is already optimized for iPhone OS.  Copying source file to destination...
/Library/Frameworks/Mono.framework/Versions/4.4.0/lib/mono/4.5/Microsoft.Common.targets : warning: Reference 'Newtonsoft.Json' not resolved
/Users/vagrant/git/plusone/ViewControllers/BaseViewController.cs(352,22) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/AccountViewController.cs(52,22) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/InterestsViewController.cs(23,30) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/InterestsViewController.cs(92,21) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(81,22) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Event/EventViewController.cs(92,22) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Event/BidConfirmedViewController.cs(17,30) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/MyPlusOne/BidderProfileViewController.cs(34,30) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/AppDelegate.cs(112,10) : warning CS0219: The variable `result' is assigned but its value is never used
/Users/vagrant/git/plusone/ViewControllers/LoginJoin/JoinViewController.cs(96,9) : warning CS0219: The variable`validationErrorMessages' is assigned but its value is never used
/Users/vagrant/git/plusone/ViewControllers/LoginJoin/LoginViewController.cs(44,23) : warning CS0168: The variable `exception' is declared but never used
/Users/vagrant/git/plusone/ViewControllers/Account/AccountViewController.cs(68,5) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/AccountViewController.cs(69,5) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/AccountViewController.cs(70,5) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/AccountViewController.cs(87,7) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/AccountViewController.cs(88,7) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/AccountViewController.cs(103,6) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/AccountViewController.cs(107,6) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/AccountViewController.cs(108,6) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/InterestsViewController.cs(42,5) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/InterestsViewController.cs(43,5) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/InterestsViewController.cs(56,21) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/InterestsViewController.cs(61,21) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/InterestsViewController.cs(64,21) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/InterestsViewController.cs(85,5) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/InterestsViewController.cs(86,5) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(70,5) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(73,5) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(292,7) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(293,7) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(294,7) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(313,6) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(318,6) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(319,6) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(356,6) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(363,6) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(371,6) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Account/ProfileViewController.cs(164,25) : warning CS0168: The variable`exception' is declared but never used
/Users/vagrant/git/plusone/ViewControllers/Event/EventsViewController.cs(321,17) : warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using `await' operator or calling`Wait' method
/Users/vagrant/git/plusone/ViewControllers/Event/EventViewController.cs(81,7) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Event/EventViewController.cs(82,7) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Event/EventViewController.cs(87,6) : warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using `await' operator
/Users/vagrant/git/plusone/ViewControllers/Event/EventViewController.cs(125,4) : warning CS0162: Unreachable code detected
/Users/vagrant/git/plusone/ViewControllers/Event/EventViewController.cs(198,5) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Event/EventViewController.cs(203,5) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/Event/EventViewController.cs(204,5) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/MyPlusOne/MyBidsViewController.cs(68,21) : warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using `await' operator
/Users/vagrant/git/plusone/ViewControllers/MyPlusOne/MyPostsViewController.cs(69,21) : warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using`await' operator
/Users/vagrant/git/plusone/ViewControllers/MyPlusOne/WatchingViewController.cs(68,21) : warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using `await' operator
/Users/vagrant/git/plusone/ViewControllers/PostEvent/EventLocationViewController.cs(116,34) : warning CS0168: The variable`geolocationException' is declared but never used
/Users/vagrant/git/plusone/ViewControllers/PostEvent/EventLocationViewController.cs(161,35) : warning CS0168: The variable `geolocationException' is declared but never used
/Users/vagrant/git/plusone/Sources/SuggestionSearchViewSource.cs(36,34) : warning CS0168: The variable`geolocationException' is declared but never used
/Users/vagrant/git/plusone/ViewControllers/MyPlusOne/WonViewController.cs(68,21) : warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using `await' operator
/Users/vagrant/git/plusone/ViewControllers/MyPlusOne/BidderProfileViewController.cs(81,5) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/MyPlusOne/BidderProfileViewController.cs(84,5) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/ViewControllers/MyPlusOne/BidderProfileViewController.cs(88,5) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/Views/MyPlus1InfoView.cs(37,6) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/Views/MyPlus1InfoView.cs(38,21) : warning CS1998: Async block lacks`await' operator and will run synchronously
/Users/vagrant/git/plusone/Views/MyPlus1InfoView.cs(39,21) : warning CS1998: Async block lacks `await' operator and will run synchronously
/Users/vagrant/git/plusone/AppDelegate.cs(168,36) : warning CS0414: The private field`plusone.AppDelegate.ApsKey' is assigned but its value is never used
/Users/vagrant/git/plusone/ViewControllers/LoginJoin/JoinEnterDetailsViewController.cs(17,15) : warning CS0169: The private field `plusone.ViewControllers.JoinEnterDetailsViewController._currentField' is never used
/Users/vagrant/git/plusone/ViewControllers/Filters/FilterBidTypeViewController.cs(15,51) : warning CS0169: The private field`plusone.FilterBidTypeViewController._viewSource' is never used
[31m#<NoMethodError: undefined method `each' for nil:NilClass>[0m
[31m--- Stack trace: ---[0m
[31m["/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise080541628/step_src/xamarin-builder/analyzer.rb:193:in `block in build_test_commands'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise080541628/step_src/xamarin-builder/analyzer.rb:168:in`each'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise080541628/step_src/xamarin-builder/analyzer.rb:168:in `build_test_commands'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise080541628/step_src/xamarin-builder/builder.rb:53:in`build_test'", "/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise080541628/step_src/step.rb:201:in `<main>'"][0m
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | [31;1mxamarin-ios-test@1.0.2 (exit code: 1)[0m                        | 100 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: ...//github.com/bitrise-steplib/steps-xamarin-ios-test/issues |
| Source: https://github.com/bitrise-steplib/steps-xamarin-ios-test            |
+----+--------------------------------------------------------------+----------+

`

**Comment by godrei** [comment]
Hi @seansparkman ,
we released a new version ([v 1.0.3](https://github.com/bitrise-steplib/steps-xamarin-ios-test/releases/tag/1.0.3)) can you please try it out and let me know if it solves this isue.
