### ISSUE TITLE
Option to skip or customize build process

### ISSUE THREAD

**Issue by Dids** [bitrise-steplib/steps-xamarin-ios-test#31]
Xamarin is deprecating xbuild, so msbuild should be used instead.

In addition to this, it would be great to either entirely skip the build task or alternatively customize the build command.

I'm facing various issues running UITests on Bitrise, and since I'm already building the targets (including the test target) with msbuild before running the tests, the extra build step is both redundant and might technically be causing issues, since it's still using xbuild.

**Comment by viktorbenei** [comment]
Hi,

These discussions should answer your question:

- https://discuss.bitrise.io/t/how-to-build-xamarin-android-and-xamarin-ios-projects-using-msbuild-instead-of-xbuild/1683
- https://discuss.bitrise.io/t/will-xamarin-15-2-2-roll-out-this-weekend-and-will-it-fix-sdk-style-csproj/1824/8

If you have any questions feel free to leave a comment there! (It's better to keep the discussion at one place where everyone can contribute to it).

**Comment by viktorbenei** [comment]
Ohh, I skipped over the feature request part of your message.

For feature requests please use: https://discuss.bitrise.io/c/feature-request
More visibility and easier tracking for everyone ;)

**Comment by Dids** [comment]
@viktorbenei Thank you, those did indeed answer my question and provided me with a workaround.
I'll try to remember to add the feature request, thanks. :D

**Comment by viktorbenei** [comment]
Glad to hear that @Dids - and if you'd have any questions feel free to ask! ;)
