### ISSUE TITLE
Error: No simulators found for OS version

### ISSUE THREAD

**Issue by merikwesterveld** [bitrise-steplib/steps-xamarin-ios-test#37]
In my project, I have setup Xamarin UI tests and want to run those tests in Bitrise. Therefore in my workflow, I run a Xamarin IOS test module. This module always returns the following error:
Failed to get simulator infos, error: No simulators found for os version: iOS 13.2.0
It doesn't matter which IOS version I use.

Is this a bug or how can I fix this?

**Comment by Roland-Bak** [comment]
Hey there @merikwesterveld, can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? :)
